service: nhl-data-pipeline
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:*
            - rds:CreateDBInstance
            - rds:DescribeDBInstances
          Resource:
            - Fn::GetAtt: [ScheduleToGameLogicQueue, Arn]

resources:
  Resources:
    ScheduleToGameLogicQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: schedule-to-game-logic-queue

    NHL:
      Type: AWS::RDS::DBInstance
      Properties:
        Engine: mysql
        EngineVersion: 5.7
        DBInstanceIdentifier: nhl
        AllocatedStorage: 20
        MasterUsername: admin
        MasterUserPassword: password
        DBInstanceClass: db.t2.micro
        PubliclyAccessible: true
        MultiAZ: false
        StorageType: gp2

functions:
  handleScheduleFeed:
    handler: src/functions/scheduleFeedHandler/handler.handleScheduleFeed
    environment:
      QUEUE_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/schedule-to-game-logic-queue"
    events:
      - eventBridge:
          schedule: rate(1 minute)
    destinations:
      onSuccess:
        type: sqs
        arn: !GetAtt [ScheduleToGameLogicQueue, Arn]
