service: nhl-data-pipeline
frameworkVersion: '3'

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:*
          Resource:
            - Fn::GetAtt: [ScheduleToGameLogicQueue, Arn]

resources:
  Resources:
    ScheduleToGameLogicQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: schedule-to-game-logic-queue

functions:
  handleScheduleFeed:
    handler: src/functions/scheduleFeedHandler/handler.handleScheduleFeed
    environment:
      QUEUE_URL: !Sub "https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/schedule-to-game-logic-queue"
    events:
      - eventBridge:
          schedule: rate(1 minute)
    destinations:
      onSuccess:
        type: sqs
        arn: !GetAtt [ScheduleToGameLogicQueue, Arn]
